base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: onevillage 
  password: '1tTak3s'
  # 'localhost' forces mysql to look for a mysql.sock on the filesystem
  # We want to force mysql to connect over the network for cases where we
  # use haproxy, so we use 127.0.0.1 here.
  host: 127.0.0.1 
  timeout: 5000

development:
  database: village_development
  <<: *base

test: &test
  database: village_test
  <<: *base
